Hello Microverse Project pull request
Habtamu210/hellom pull request #1
Opened 2022-09-21 11:04 UTC by Habtamu210

2022-09-21 11:58 UTC, Santiago220991 requested changes
Hi @Habtamu210 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
:heavy_check_mark: Meaningful name branch.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Correct GitHub flow.

## Required Changes ♻️

- Kindly customize the README file using the template provided by Microverse [Link](https://github.com/microverseinc/readme-template). This is a project requirement. :scroll: 
- Kindly edit the Pull Request it should have a meaningful title and a short summary describing the introduced changes. This is also a project requirement. :scroll: 

_Also please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 11:58 UTC, Santiago220991 commented on A.css
> +}
- [OPTIONAL] Please remember that the commit messages should be descriptive, written in the imperative tense, and capitalized. For example in this case could be:  "Add xxxx.css file."  :nerd_face:

2022-09-21 11:58 UTC, Santiago220991 commented on A.html
> +</html>
- [OPTIONAL] Same here the commit message should be descriptive. For example, Add xxxx.html file. :grin:

2022-09-22 07:13 UTC, topeogunleye requested changes
Hi @Habtamu210, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:

## Required Changes ♻️
- [ ] As suggested by the previous reviewer, I kindly suggest that you add a more descriptive PR title and description. 
## EXAMPLE :
```
## Hello Microverse
In this Pull Request, I:
- Created branches with different base branches.
- Followed GitHub flow.
- Added a descriptive and easy to understand README
- Added a HTML file
- Added a CSS File
- Added a h1 text of "Hello-World"
```
https://user-images.githubusercontent.com/52934128/176308229-e31b2c8d-110b-4823-a2a8-31c1b7d7c73d.mp4

- [ ] I suggest you kindly edit your [README](https://github.com/AkashaSedeqi/HelloMicroverse/blob/base-branch/README.md) file to your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project. Here is demo below

https://user-images.githubusercontent.com/52934128/176309876-98f49c4e-3e62-4edd-9bf3-51a66f48e2cd.mp4

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 10:56 UTC, merged

2022-09-22 11:19 UTC, bobb-Rob reviewed
## STATUS: CHANGES REQUIRED ♻️

Hi @Habtamu210 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Neat Commit messages


 ## Required Changes ♻️

- [ ] Please refer to the previous reviewer comments about a descriptive pull request. He gave you and example that you should follow. Kindly implement it. This is important for your future projects as well. Providing a descriptive title and summary for your PR helps your collaborators know what you did.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 12:45 UTC, Habtamu210 commented
HI
"Please refer to the previous reviewer's comments about a descriptive pull
request."
where can I include these comments put in quotations in pull requests?
Thank you!

On Thu, Sep 22, 2022 at 4:20 AM Robertson Arthur ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> STATUS: CHANGES REQUIRED ♻️
>
> Hi @Habtamu210 <https://github.com/Habtamu210> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
>
> <https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966>
> Highlights
>
> ✅ No Linter error
> ✅ Correct use of GitHub flow
> ✅ Neat Commit messages
> Required Changes ♻️
>
>    - Please refer to the previous reviewer comments about a descriptive
>    pull request. He gave you and example that you should follow. Kindly
>    implement it. This is important for your future projects as well. Providing
>    a descriptive title and summary for your PR helps your collaborators know
>    what you did.
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Habtamu210/hellom/pull/1#pullrequestreview-1116857808>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AISVLPZ6O43O7U3AWJBOLVDV7Q6GPANCNFSM6AAAAAAQR6OQTM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-22 13:04 UTC, Olamarx reviewed
Hi @Habtamu210, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that can not be reviewed because it has been merged. I can't see the linters and some other features because you have merged it. Kindly always submit for review and make sure it is approved before you merge it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._